# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-19 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0006_temporarydocumenttext_hash_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_title', models.CharField(max_length=255, unique=True, verbose_name='Url title')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='External link')),
                ('visit_count', models.IntegerField(default=0, verbose_name='Visit count')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last access')),
                ('last_access', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last access')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortlinks', to='documents.Document', verbose_name='Document')),
            ],
        ),
    ]
