# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_edit_minutes_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='documents.Document', verbose_name='Document'),
        ),
    ]
