# Generated by Django 2.1.10 on 2019-07-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_add_on_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order'], 'permissions': (('show_menuitem', 'User/Group is allowed to view this menu item'), ('changechildren_menuitem', 'User/Group is allowed to change children items'))},
        ),
    ]
