# Generated by Django 2.0.13 on 2019-07-21 08:51
from django.db import migrations, models


def initial_data(apps, _schema_editor):
	MenuItem = apps.get_model("main", "MenuItem")

	for item in MenuItem.objects.all():
		item.title_en = item.title_de
		item.save()


def reverse_initial_data(_apps, _schema_editor):
	pass


class Migration(migrations.Migration):
	dependencies = [
		('main', '0014_add_on_delete'),
	]

	operations = [
		migrations.RenameField(
			model_name='menuitem',
			old_name='title',
			new_name='title_de',
		),
		migrations.AddField(
			model_name='menuitem',
			name='title_en',
			field=models.CharField(max_length=255, null=True, verbose_name='Title (english)'),
			preserve_default=False,
		),

		migrations.RunPython(initial_data, reverse_initial_data),

		migrations.AlterField(
			model_name='menuitem',
			name='title_de',
			field=models.CharField(max_length=255, null=False, verbose_name='Title (german)'),
		),

		migrations.AlterField(
			model_name='menuitem',
			name='title_en',
			field=models.CharField(max_length=255, null=False, verbose_name='Title (english)'),
		),
	]
