# Generated by Django 2.2.7 on 2019-11-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190721_1051'),
        ('main', '0015_rename_view_permission'),
    ]

    operations = [
    ]
