# Generated by Django 2.2.10 on 2020-03-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_merge_20191118_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='title_de',
            field=models.CharField(max_length=255, verbose_name='Title (German)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Title (English)'),
        ),
    ]
