# Generated by Django 3.0.13 on 2021-03-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=64, unique=True)),
                ('list_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LegacyAdminURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_url', models.CharField(max_length=32)),
                ('hash_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_admin_url', to='tenca_django.HashEntry')),
            ],
        ),
    ]
