# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-25 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information_pages', '0003_auto_20180201_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationdocument',
            options={'permissions': (('view_informationdocument', 'User/Group is allowed to view that document'),), 'verbose_name': 'Information document', 'verbose_name_plural': 'Information documents'},
        ),
    ]
