# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('information_pages', '0004_auto_20180813_2050'), ('information_pages', '0005_auto_20180813_2102')]

    dependencies = [
        ('information_pages', '0003_auto_20180201_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationdocument',
            options={'base_manager_name': 'objects', 'permissions': (('view_informationdocument', 'User/Group is allowed to view that document'),), 'verbose_name': 'Information document', 'verbose_name_plural': 'Information documents'},
        ),
    ]
