# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_pages', '0005_auto_20180825_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationdocument',
            name='show_author_to',
            field=models.IntegerField(choices=[(0, 'No one'), (1, 'Logged in users'), (2, 'Everyone')], default=1, verbose_name='Show author to'),
        ),
    ]
