# Generated by Django 2.1.10 on 2019-07-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information_pages', '0005_auto_20180825_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationdocument',
            options={'base_manager_name': 'objects', 'permissions': (('show_informationdocument', 'User/Group is allowed to view that document'),), 'verbose_name': 'Information document', 'verbose_name_plural': 'Information documents'},
        ),
    ]
