# Generated by Django 2.2.11 on 2020-03-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information_pages', '0006_informationdocument_show_author_to'),
        ('information_pages', '0006_rename_view_permission'),
    ]

    operations = [
    ]
