# Generated by Django 2.0.7 on 2018-07-23 13:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('polls', '0001_initial'), ('polls', '0002_auto_20160314_1851'), ('polls', '0003_auto_20160509_1652'), ('polls', '0004_auto_20160530_1932'), ('polls', '0005_auto_20160606_1805'), ('polls', '0006_poll_show_results_immediately')]

    initial = True

    dependencies = [
        ('documents', '0002_auto_20160321_1755'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('votes', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=0, verbose_name='ordering index')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('start_date', models.DateField(default=datetime.datetime.now, verbose_name='Start Date')),
                ('end_date', models.DateField(default=datetime.datetime.now, verbose_name='End Date')),
                ('max_allowed_number_of_answers', models.PositiveIntegerField(default=1)),
                ('participants', models.ManyToManyField(blank=True, related_name='polls', to=settings.AUTH_USER_MODEL)),
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('show_results_immediately', models.BooleanField(default=True, verbose_name='show results immediately after vote')),
            ],
            options={
                'permissions': (('view_poll', 'User/Group is allowed to view that poll'), ('vote_poll', 'User/Group is allowed to participate (vote) in that poll')),
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.Poll'),
        ),
    ]
