# Generated by Django 2.0.13 on 2019-07-08 15:58

from django.db import migrations, models
import django.utils.timezone


def copy_german_texts_and_descriptions(apps, _schema_editor):
    Choice = apps.get_model("polls", "Choice")
    for choice in Choice.objects.all():
        if not choice.description_en:
            choice.description_en = choice.description_de
        if not choice.text_en:
            choice.text_en = choice.text_de
        choice.save()


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_squashed_0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='description',
            new_name='description_de',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='text_de',
        ),
        migrations.AlterField(
            model_name='choice',
            name='description_de',
            field=models.TextField(blank=True, default='', verbose_name='description (german)'),
        ),
        migrations.AddField(
            model_name='choice',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='description (english)'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text_de',
            field=models.CharField(default=1, max_length=255, verbose_name='text (german)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='text_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='text (english)'),
            preserve_default=False,
        ),
        migrations.RunPython(copy_german_texts_and_descriptions, reverse_code=migrations.RunPython.noop),
    ]
