# Generated by Django 2.0.13 on 2019-07-08 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_squashed_0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='text',
        ),
        migrations.AddField(
            model_name='choice',
            name='description_de',
            field=models.TextField(blank=True, default='', verbose_name='description (german)'),
        ),
        migrations.AddField(
            model_name='choice',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='description (english)'),
        ),
        migrations.AddField(
            model_name='choice',
            name='text_de',
            field=models.CharField(default=1, max_length=255, verbose_name='text (german)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='text_en',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='text (english)'),
            preserve_default=False,
        ),
    ]
