# Generated by Django 2.1.10 on 2019-07-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_squashed_0006_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'permissions': (('show_poll', 'User/Group is allowed to view that poll'), ('vote_poll', 'User/Group is allowed to participate (vote) in that poll'))},
        ),
    ]
