# Generated by Django 2.2.7 on 2019-11-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_view_permission'),
        ('polls', '0002_auto_20190708_1758'),
    ]

    operations = [
    ]
