# Generated by Django 2.2.10 on 2020-03-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_merge_20191118_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='description_de',
            field=models.TextField(blank=True, default='', verbose_name='Description (German)'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='index',
            field=models.IntegerField(default=0, verbose_name='Ordering index'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text_de',
            field=models.CharField(max_length=255, verbose_name='Text (German)'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text_en',
            field=models.CharField(max_length=255, verbose_name='Text (English)'),
        ),
    ]
