# Generated by Django 2.2.11 on 2020-03-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200302_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='show_results_immediately',
        ),
        migrations.AddField(
            model_name='poll',
            name='state',
            field=models.IntegerField(choices=[(0, 'Unpublished'), (1, 'Published After End of Poll'), (2, 'Published')], default=0, verbose_name='State'),
        ),
    ]
