# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-13 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_poll_show_results_immediately'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'permissions': (('view_poll', 'User/Group is allowed to view that poll'), ('vote_poll', 'User/Group is allowed to participate (vote) in that poll')), 'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
    ]
