# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-25 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0009_auto_20180201_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minutesdocument',
            options={'permissions': (('view_minutesdocument', 'User/Group is allowed to view those minutes'),), 'verbose_name': 'Minutes', 'verbose_name_plural': 'Minutes'},
        ),
    ]
