# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('minutes', '0010_auto_20180813_2050'), ('minutes', '0011_auto_20180813_2102')]

    dependencies = [
        ('minutes', '0009_auto_20180201_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minutesdocument',
            options={'base_manager_name': 'objects', 'permissions': (('view_minutesdocument', 'User/Group is allowed to view those minutes'),), 'verbose_name': 'Minutes', 'verbose_name_plural': 'Minutes'},
        ),
    ]
