# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-30 10:35
from __future__ import unicode_literals

import _1327.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20161213_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='hash_value',
            field=models.CharField(default=_1327.documents.models.Attachment.get_hash, max_length=40, unique=True, verbose_name='Hash value'),
        ),
    ]
