# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-27 16:29
from __future__ import unicode_literals

import _1327.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('documents', '0006_5_auto_20170227_1812'),
	]

	operations = [
		migrations.RemoveField(
			model_name='temporarydocumenttext',
			name='hash_value',
		),
		migrations.AddField(
			model_name='document',
			name='hash_value',
			field=models.CharField(default=_1327.documents.models.Document.get_hash, max_length=40, null=True, verbose_name='Hash value'),
		),
	]
