# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-27 16:48
from __future__ import unicode_literals

import datetime
import hashlib

from django.db import migrations, models


def fill_hash_values(apps, schema_editor):
	Document = apps.get_model("documents", "Document")
	for document in Document.objects.all():
		max_id = Document.objects.aggregate(models.Max('id'))['id__max'] or 0
		hash_value = '{}_{}'.format(hashlib.md5(str(datetime.datetime.now()).encode()).hexdigest(), int(max_id) + 1)
		document.hash_value = hash_value
		document.save()


def reverse_fill_hash_values(apps, schema_editor):
	# no need to do anything here, but we need this function because Django won't let us reverse the migration otherwise
	pass


class Migration(migrations.Migration):

	dependencies = [
		('documents', '0007_auto_20170227_1729'),
	]

	operations = [
		migrations.RunPython(fill_hash_values, reverse_code=reverse_fill_hash_values),
	]
