# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-27 16:48
from __future__ import unicode_literals

from django.db import migrations

import _1327.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('documents', '0008_auto_20170227_1748'),
	]

	operations = [
		migrations.AlterField(
			model_name='document',
			name='hash_value',
			field=models.CharField(default=_1327.documents.models.Document.get_hash, max_length=40, unique=True, verbose_name='Hash value'),
		),
	]
