# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('documents', '0010_add_on_delete'),
	]

	operations = [
		migrations.AlterField(
			model_name='document',
			name='text',
			field=models.TextField(blank=True, null=True),
		),
		migrations.RenameField(
			model_name='document',
			old_name='text',
			new_name='text_de',
		),
		migrations.AlterField(
			model_name='document',
			name='text_de',
			field=models.TextField(blank=True, null=True, verbose_name='text (german)'),
		),
		migrations.AlterField(
			model_name='document',
			name='title',
			field=models.CharField(blank=True, max_length=255, null=False),
		),
		migrations.RenameField(
			model_name='document',
			old_name='title',
			new_name='title_de',
		),
		migrations.AlterField(
			model_name='document',
			name='title_de',
			field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title (german)'),
		),
		migrations.AddField(
			model_name='document',
			name='text_en',
			field=models.TextField(blank=True, null=True, verbose_name='text (english)'),
		),
		migrations.AddField(
			model_name='document',
			name='title_en',
			field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title (english)'),
		),
	]
