# Generated by Django 2.1.10 on 2019-07-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_add_on_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': (('show_document', 'User/Group is allowed to view that document'),), 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
    ]
