# Generated by Django 2.0.9 on 2018-12-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20180827_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarydocumenttext',
            name='text',
        ),
        migrations.AddField(
            model_name='temporarydocumenttext',
            name='text_de',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='temporarydocumenttext',
            name='text_en',
            field=models.TextField(blank=True),
        ),
    ]
