# Generated by Django 2.0.9 on 2018-10-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20180827_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='text_de',
            field=models.TextField(blank=True, null=True, verbose_name='text (german)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='text (english)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title (german)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title (english)'),
        ),
    ]
