# Generated by Django 2.0.13 on 2019-03-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20181228_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title_de',
            field=models.CharField(max_length=255, verbose_name='title (german)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='title (english)'),
        ),
    ]
