# Generated by Django 2.2.7 on 2019-11-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20190311_2120'),
        ('documents', '0011_rename_view_permission'),
    ]

    operations = [
    ]
