# Generated by Django 2.0.9 on 2018-12-07 14:45

import _1327.emails.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='email',
            name='trello_card_id',
        ),
        migrations.AlterField(
            model_name='email',
            name='envelope',
            field=models.FileField(upload_to=_1327.emails.models.upload_path),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['date'], name='emails_emai_date_bd689a_idx'),
        ),
    ]
